encoding: utf-8

# SEO相关信息
title: Fujao-time 时报
description: 啊wee改哈鞥嫦娥我刚不疤痕处哈维楚王嗡阿格王朔！！！111111
keywords: 
author: Fujao-time 编辑部
footerText: '(C) 2020 FJT / Under CC BY-NC-ND 4.0 & SATA License'

# 链接格式
permalink: /posts/:title.html
# permalink: /posts/:year/:month/:day/:title.html

# 这些不要动
kramdown:
  auto_ids: true
  input: GFM
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'cli.bat', 'dist.tar.gz']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: 'https://fujao-time.qmqaq.top'
baseurl: ''

# 菜单
menu:
  - title: 首页
    url: /
  - title: 归类
    url: /pages/categories.html
  - title: 搜索
    url: /pages/search.html
  - title: 友链
    url: /pages/links.html
  - title: 关于
    url: /pages/about.html

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: true

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 腾讯MTA移动分析,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extMTA: false

# 百度收录自动推送,不需要请设置为false
extBaidu: true

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: false

# 友情链接
links:
  - title: Cytoid
    url: https://cytoid.io
  - title: 符语大全
    url: https://fujao-time.qmqaq.top/fujaoese-hitokoto/fujaoese.html
  - title: FJT 编辑部档案
    url: https://fujao-time.qmqaq.top/fujaoese-hitokoto/